### PR TITLE
[Does not need CI check] Branch lost commits b18a4898 & c4303310, fixes haskell-nix/hnix#536

### PR DESCRIPTION
**Pull request by Anton-Latukha**
Solves https://github.com/haskell-nix/hnix/issues/536.

In short. Some people use these states - they need to be accessible through `git`, as they were before.

```fish
# Clonning haskell-nix/nix fork
#
🅸 ~/s/haskell> git clone https://github.com/haskell-nix/nix.git
Cloning into 'nix'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 45166 (delta 32), reused 17 (delta 17), pack-reused 45126
Receiving objects: 100% (45166/45166), 19.48 MiB | 701.00 KiB/s, done.
Resolving deltas: 100% (29057/29057), done.
🅸 ~/s/haskell>cd nix
🅸 ~/s/h/nix:master◦> git checkout b18a4898ff990c0b8ec1d3571d23a054a7d4c5cd
fatal: reference is not a tree: b18a4898ff990c0b8ec1d3571d23a054a7d4c5cd
```

There is no way in git to get those commits from repo.

This PR reintroduces the original commits back into the `haskell-nix/nix` repo branches tree graph.

```fish
# Clonning my fork
#
🅸 ~/s/haskell>git clone git@github.com:Anton-Latukha/nix.git
Cloning into 'nix'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 46641 (delta 32), reused 17 (delta 17), pack-reused 46601
Receiving objects: 100% (46641/46641), 21.07 MiB | 633.00 KiB/s, done.
Resolving deltas: 100% (29857/29857), done.
🅸 ~/s/haskell>cd nix
🅸 ~/s/h/nix:master◦>git checkout b18a4898ff990c0b8ec1d3571d23a054a7d4c5cd
Note: switching to 'b18a4898ff990c0b8ec1d3571d23a054a7d4c5cd'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at b18a4898 Merge remote-tracking branch 'upstream/master'
🅸 ~/s/h/nix:b18a4898>
```

This PR is just a simple return of checkout of the old b18a4898.

This does not need CI check, since this PR is for purposes of proper archiving the git objects.

Since is not possible on GitHub to create a PR that merges into the new branch - I opened PR to the master. So, please, branch this and treat as an archive branch.

### CODE REVIEW

**Comment by jwiegley** [comment]
Ah, this is just a fork of `NixOS/nix`, I'm afraid. You'll need to submit this PR to the original project.

**Comment by Anton-Latukha** [comment]
Then can you briefly say what is the technical issue with the commits was, since they are in object storage of `haskell-nix/hnix` and were checking out.

**Comment by jwiegley** [comment]
@Anton-Latukha I do thank you for the contribution. The reason I don't accept the PR here is that I don't want to maintain a fork of `nix`. However, the process you suggest of tagging any commit that our submodule depends on, and pushing that tag here, is a good one, and I'll make it part of our release process.

I appreciate your thoughtfulness, and the energy you've spent, and would find it unfortunate if you really thought I/we don't embrace cooperation here at the hnix project.

**Comment by jwiegley** [comment]
@Anton-Latukha No apologies needed, Anton! GitHub PR comments are a notoriously difficult medium for communicating when we haven't met yet to synchronize our reading of intention and nuance.

As for exception handling, I'm happy for whatever sort of contributions would also help you in your pursuit of better Haskell engineering. I'm sure we could do much better in this area. Do you have a design proposals in mind for future work you'd like to add to hnix? Feel free to create a ticket within the hnix repo for this, and we'll move the present discussion there.

**Pull request closed without merging**
